name: Build and Deploy

on: 
  push:
    branches-ignore:
      - 'paper-*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build all versions
        uses: satackey/action-docker-layer-caching@v0.0.10
        continue-on-error: true
        run: source ./bin/travis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get current branch name
        id: extract_branch_name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: Get current date
        id: current_date
        run: echo "##[set-output name=date;]$(echo $(date -u '+%m-%d'))"
      - name: Build tag id
        id: build_tag
        run: echo "##[set-output name=tag]$(echo paper-${{ steps.extract_branch_name.branch }}-${{ steps.current_date.date }}-r$GITHUB_RUN_ID)"
      - name: Upload release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.build_tag.tag }}
          file: ./rel/*
          file_glob: true
          overwrite: true
          body: "Github Actions Auto-Release"